# Generated by Django 5.2.7 on 2025-10-23 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('summary', models.TextField(help_text='Расскажите о себе', verbose_name='О себе')),
                ('education', models.TextField(help_text='Учебное заведение', verbose_name='Образование')),
                ('experience', models.TextField(help_text='Места работы', verbose_name='Опыт работы')),
                ('languages', models.TextField(blank=True, help_text='Какой язык знаете', verbose_name='Языки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Резюме',
                'verbose_name_plural': 'Резюме',
            },
        ),
    ]
