# Generated by Django 5.2.7 on 2025-10-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='email',
            field=models.EmailField(help_text='Введите корректный email адрес', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='full_name',
            field=models.CharField(help_text='Введите фамилию, имя и отчество через пробел', max_length=100, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='phone',
            field=models.CharField(help_text='Введите номер телефона (11 цифр, начинается с 7 или 8)', max_length=20, verbose_name='Телефон'),
        ),
    ]
